.TH view-toolpaths "1" "August 2014" "view-toolpaths" "User Commands"
.SH NAME
config-bundle-to-config \- Dump a Slic3r config from a config bundle

.SH SYNOPSIS
.B config-bundle-to-config \-\-output \fIconfig.ini\fR \fIbundle.ini\fR

.SH DESCRIPTION
config-bundle-to-config is a tool that converts a Slic3r config bundle into a
config.ini that can be fed into \fIview-toolpaths(1)\fR and \fIslic3r(1)\fR

.SH OPTIONS
.TP
\fB\-\-output\fR \fIconfig.ini\fR
Dump configuration into \fIconfig.ini\fR
