.TH dump-stl "1" "June 2014" "dump-stl" "User Commands"
.SH NAME
dump-stl \- Dump STL into Perl syntax for writing Slic3r tests

.SH SYNOPSIS
.B dump-stl \fIfile.stl\fR
.br
.B dump-stl \fImodelname\fR \fIfile.stl\fR

.SH DESCRIPTION
dump-stl is a script which dumps an STL file into Perl syntax for writing Slic3r
tests, or dumps a test model into an STL file.
