.TH split_stl "1"
.SH NAME
split_stl \- Split STL plate into multiple files
.SH SYNOPSIS
.B split_stl
[ \fIOPTIONS \fR] \fIfile.stl\fR
.SH DESCRIPTION
split_stl splits an STL model into multiple STL files, one per piece inside the
original STL file.
.SH OPTIONS
.TP
\fB\-\-help\fR
Output this usage screen and exit
.TP
\fB\-\-ascii\fR
Generate ASCII STL files (default: binary)
