.TH amf-to-stl "1"
.SH NAME
stl-to-amf \- Combine multiple STL files into one AMF file
.SH SYNOPSIS
.B amf-to-stl
[ \fIOPTIONS \fR] \fIfile.stl \fR[ \fIfile2.stl \fR[ \fIfile3.stl \fR] ]
.SH DESCRIPTION
stl-to-amf is a script which combines STL files into an AMF file for multiple
extrusion.
.SH OPTIONS
.TP
\fB\-\-help\fR
Output this usage screen and exit
.HP
\fB\-\-distinct\-materials\fR Assign each STL file to a different material
