.TH view-mesh "1"
.SH NAME
view-mesh \- STL mesh viewer
.SH SYNOPSIS
.B view-mesh
[ \fIOPTIONS \fR] \fIfile.stl\fR
.SH DESCRIPTION
view-mesh is a mesh viewer that renders an STL file and allows the view to be
panned using a mouse. Primary click pans the view, while secondary-click shifts
the model.
.SH OPTIONS
.TP
\fB\-\-help\fR
Output this usage screen and exit
