.TH view-toolpaths "1" "August 2014" "view-toolpaths" "User Commands"
.SH NAME
view-toolpaths \- Preview slic3r toolpath by layer

.SH SYNOPSIS
.B view-toolpaths [ \fIOPTIONS\fR ] \fIfile.stl\fR

.SH DESCRIPTION
view-toolpaths is a tool for visualizing the toolpath that will be exported into
G-code by Slic3r for a given config.

.SH OPTIONS
.TP
\fB\-\-help\fR
Output this usage screen and exit

.TP
\fB\-\-load\FR \fICONFIG\fR
Loads the supplied config file
